---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/webps
    username:
      from_secret: quay_username

...
