// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package webpspb is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ListRequest
	ListResponse
	Container
*/
package webpspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListResponse struct {
	Container []*Container `protobuf:"bytes,1,rep,name=container" json:"container,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListResponse) GetContainer() []*Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type Container struct {
	Name                string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image               string            `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Status              string            `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	DockerComposeLabels map[string]string `protobuf:"bytes,4,rep,name=docker_compose_labels,json=dockerComposeLabels" json:"docker_compose_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Container) GetDockerComposeLabels() map[string]string {
	if m != nil {
		return m.DockerComposeLabels
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "webpspb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "webpspb.ListResponse")
	proto.RegisterType((*Container)(nil), "webpspb.Container")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WebPsBackend service

type WebPsBackendClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type webPsBackendClient struct {
	cc *grpc.ClientConn
}

func NewWebPsBackendClient(cc *grpc.ClientConn) WebPsBackendClient {
	return &webPsBackendClient{cc}
}

func (c *webPsBackendClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/webpspb.WebPsBackend/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WebPsBackend service

type WebPsBackendServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterWebPsBackendServer(s *grpc.Server, srv WebPsBackendServer) {
	s.RegisterService(&_WebPsBackend_serviceDesc, srv)
}

func _WebPsBackend_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebPsBackendServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webpspb.WebPsBackend/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebPsBackendServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebPsBackend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webpspb.WebPsBackend",
	HandlerType: (*WebPsBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _WebPsBackend_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbf, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x49, 0x13, 0x2b, 0x79, 0xad, 0x20, 0xcf, 0x56, 0x8e, 0x4e, 0x25, 0x53, 0x41, 0x08,
	0xd2, 0x2e, 0xe2, 0x24, 0x46, 0x9d, 0x3a, 0x48, 0x16, 0xc7, 0x70, 0x49, 0x1e, 0x12, 0x92, 0xdc,
	0x9d, 0xb9, 0x8b, 0xd2, 0x7f, 0xdc, 0x59, 0x72, 0x89, 0x51, 0x2c, 0x6e, 0xf7, 0xfd, 0xf1, 0xe0,
	0xc3, 0xf7, 0xc0, 0xe7, 0xaa, 0x08, 0x55, 0x23, 0x8d, 0xc4, 0xd3, 0x0f, 0x4a, 0x95, 0x56, 0x69,
	0x70, 0x06, 0xb3, 0x7d, 0xa1, 0x4d, 0x4c, 0x6f, 0x2d, 0x69, 0x13, 0xdc, 0xc1, 0xbc, 0x97, 0x5a,
	0x49, 0xa1, 0x09, 0xaf, 0xc1, 0xcf, 0xa4, 0x30, 0xbc, 0x10, 0xd4, 0x30, 0x67, 0xed, 0x6e, 0x66,
	0x5b, 0x0c, 0x87, 0xdb, 0x30, 0xfa, 0x4e, 0xe2, 0x9f, 0x52, 0xf0, 0xe9, 0x80, 0x3f, 0x06, 0x88,
	0xe0, 0x09, 0x5e, 0x13, 0x73, 0xd6, 0xce, 0xc6, 0x8f, 0xed, 0x1b, 0x17, 0x70, 0x52, 0xd4, 0xfc,
	0x95, 0xd8, 0xc4, 0x9a, 0xbd, 0xc0, 0x4b, 0x98, 0x6a, 0xc3, 0x4d, 0xab, 0x99, 0x6b, 0xed, 0x41,
	0x61, 0x02, 0xcb, 0x5c, 0x66, 0x25, 0x35, 0x49, 0x26, 0x6b, 0x25, 0x35, 0x25, 0x15, 0x4f, 0xa9,
	0xd2, 0xcc, 0xb3, 0x34, 0x57, 0xc7, 0x34, 0xe1, 0x83, 0xed, 0x47, 0x7d, 0x7d, 0x6f, 0xdb, 0x8f,
	0xc2, 0x34, 0x87, 0xf8, 0x22, 0x3f, 0x4e, 0x56, 0x4f, 0xc0, 0xfe, 0x3b, 0xc0, 0x73, 0x70, 0x4b,
	0x3a, 0x0c, 0xf4, 0xdd, 0xb3, 0x83, 0x7f, 0xe7, 0x55, 0x3b, 0xc2, 0x5b, 0x71, 0x3b, 0xb9, 0x71,
	0xb6, 0x11, 0xcc, 0x5f, 0x28, 0x7d, 0xd6, 0xf7, 0x3c, 0x2b, 0x49, 0xe4, 0xb8, 0x03, 0xaf, 0x9b,
	0x12, 0x17, 0x23, 0xe1, 0xaf, 0xa1, 0x57, 0xcb, 0x3f, 0x6e, 0xbf, 0x77, 0x3a, 0xb5, 0xdf, 0xb3,
	0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x57, 0x87, 0x30, 0xf6, 0xab, 0x01, 0x00, 0x00,
}
